// This code is generated by generate_code.py, do not modify it manually.

enum Metallicity {
    /// Z = 0.0001
    Z0p0001,
    /// Z = 0.0002
    Z0p0002,
    /// Z = 0.0005
    Z0p0005,
    /// Z = 0.0010
    Z0p0010,
    /// Z = 0.0020
    Z0p0020,
    /// Z = 0.0040
    Z0p0040,
    /// Z = 0.0060
    Z0p0060,
    /// Z = 0.0080
    Z0p0080,
    /// Z = 0.0100
    Z0p0100,
    /// Z = 0.0140
    Z0p0140,
    /// Z = 0.0170
    Z0p0170,
    /// Z = 0.0200
    Z0p0200,
    /// Z = 0.0300
    Z0p0300,
    /// Z = 0.0400
    Z0p0400,
    /// Z = 0.0600
    Z0p0600,
}

impl Metallicity {
    fn to_archive_name(&self) -> &str {
        match self {
            Metallicity::Z0p0001 => "Z0.0001Y0.249.tar.gz",
            Metallicity::Z0p0002 => "Z0.0002Y0.249.tar.gz",
            Metallicity::Z0p0005 => "Z0.0005Y0.249.tar.gz",
            Metallicity::Z0p0010 => "Z0.001Y0.25.tar.gz",
            Metallicity::Z0p0020 => "Z0.002Y0.252.tar.gz",
            Metallicity::Z0p0040 => "Z0.004Y0.256.tar.gz",
            Metallicity::Z0p0060 => "Z0.006Y0.259.tar.gz",
            Metallicity::Z0p0080 => "Z0.008Y0.263.tar.gz",
            Metallicity::Z0p0100 => "Z0.01Y0.267.tar.gz",
            Metallicity::Z0p0140 => "Z0.014Y0.273.tar.gz",
            Metallicity::Z0p0170 => "Z0.017Y0.279.tar.gz",
            Metallicity::Z0p0200 => "Z0.02Y0.284.tar.gz",
            Metallicity::Z0p0300 => "Z0.03Y0.302.tar.gz",
            Metallicity::Z0p0400 => "Z0.04Y0.321.tar.gz",
            Metallicity::Z0p0600 => "Z0.06Y0.356.tar.gz",
        }
    }

    fn to_mass_fraction(&self) -> f32 {
        match self {
            Metallicity::Z0p0001 => 0.0001,
            Metallicity::Z0p0002 => 0.0002,
            Metallicity::Z0p0005 => 0.0005,
            Metallicity::Z0p0010 => 0.001,
            Metallicity::Z0p0020 => 0.002,
            Metallicity::Z0p0040 => 0.004,
            Metallicity::Z0p0060 => 0.006,
            Metallicity::Z0p0080 => 0.008,
            Metallicity::Z0p0100 => 0.01,
            Metallicity::Z0p0140 => 0.014,
            Metallicity::Z0p0170 => 0.017,
            Metallicity::Z0p0200 => 0.02,
            Metallicity::Z0p0300 => 0.03,
            Metallicity::Z0p0400 => 0.04,
            Metallicity::Z0p0600 => 0.06,
        }
    }

    fn to_dex(self) -> f32 {
        match self {
            todo!()
        }
    }
}
