// This code is generated by generate_code.py, do not modify it manually.

//! Provides access to an enum for the available metallicities, arrays of masses for each metallicity, and several helper functions.

pub(crate) mod data;
pub mod masses;
pub mod metallicity;
