// This code is generated by generate_code.py, do not modify it manually.

pub(crate) const PARSEC_URL: &str = "https://people.sissa.it/~sbressan/CAF09_V1.2S_M36_LT/";

pub(crate) mod data;
pub(crate) mod masses;
pub(crate) mod metallicity;
