// This code is generated by generate_code.py, do not modify it manually.

//! Provides access to an enum for the available metallicities, arrays of masses for each metallicity, and several helper functions.

pub(crate) const PARSEC_URL: &str = "https://people.sissa.it/~sbressan/CAF09_V1.2S_M36_LT/";

pub(crate) mod data;
pub mod masses;
pub mod metallicity;
