name: Check for TODOs

on: [pull_request]

jobs:
    check:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Check for TODOs
                run: ./scripts/list_todos.sh
